CREATE TABLE PHONG_BAN (
    PHONG_BAN_ID NVARCHAR2(4) PRIMARY KEY,
    TEN_PHONG_BAN NVARCHAR2(20) NOT NULL
);

CREATE TABLE CHUC_VU (
    CHUC_VU_ID NVARCHAR2(4) PRIMARY KEY,
    TEN_CHUC_VU NVARCHAR2(20) NOT NULL
);

CREATE TABLE NHAN_VIEN (
    NHAN_VIEN_ID NVARCHAR2(4) PRIMARY KEY,
    PHONG_BAN_ID NVARCHAR2(4) NOT NULL,
    CHUC_VU_ID NVARCHAR2(4) NOT NULL,
    HO NVARCHAR2(20),
    DEM NVARCHAR2(20),
    TEN NVARCHAR2(20) NOT NULL,
    NGAY_SINH DATE NOT NULL,
    FOREIGN KEY (PHONG_BAN_ID) REFERENCES PHONG_BAN(PHONG_BAN_ID),
    FOREIGN KEY (CHUC_VU_ID) REFERENCES CHUC_VU(CHUC_VU_ID)
);

CREATE TABLE QUAN_LY (
    CAP_TREN_ID NVARCHAR2(4) NOT NULL,
    CAP_DUOI_ID NOT NULL,
    PRIMARY KEY (CAP_TREN_ID, CAP_DUOI_ID),
    FOREIGN KEY (CAP_TREN_ID) REFERENCES NHAN_VIEN(NHAN_VIEN_ID),
    FOREIGN KEY (CAP_DUOI_ID) REFERENCES NHAN_VIEN(NHAN_VIEN_ID)
)

CREATE TABLE LUONG (
    LUONG_ID NVARCHAR2(4) PRIMARY KEY,
    NHAN_VIEN_ID NVARCHAR2(4) NOT NULL,
    LUONG_TU_NGAY DATE NOT NULL,
    LUONG NUMBER(10,2) NOT NULL,
    FOREIGN KEY (NHAN_VIEN_ID) REFERENCES NHAN_VIEN(NHAN_VIEN_ID)
)