DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE (
    DEPARTMENT NVARCHAR2(20) NOT NULL,
    EMPLOYEE_ID NUMBER(4) PRIMARY KEY,
    EMPLOYEE_NAME NVARCHAR2(20),
    JOB_POSITION NVARCHAR2(20),
    MANAGER NVARCHAR2(20),
    SALARY NUMBER(8,2),
    DATE_OF_BIRTH DATE
);

INSERT INTO EMPLOYEE (DEPARTMENT, EMPLOYEE_ID, EMPLOYEE_NAME, JOB_POSITION, MANAGER, SALARY, DATE_OF_BIRTH)
VALUES ('Tech', '002', 'Nguy?n ?ình Sang', 'Fresher Mobile', 'Manager', '123456', TO_DATE('09-01-1999', 'dd-mm-yyyy'));