INSERT INTO EMPLOYEE (DEPARTMENT, EMPLOYEE_ID, EMPLOYEE_NAME, JOB_POSITION, MANAGER, SALARY, DATE_OF_BIRTH)
VALUES ('Tech', '1', 'Nguy?n ?ình Sang', 'Fresher Mobile', 'Manager', '123456', TO_DATE('09-01-1999', 'dd-mm-yyyy'));

INSERT INTO EMPLOYEE (DEPARTMENT, EMPLOYEE_ID, EMPLOYEE_NAME, JOB_POSITION, MANAGER, SALARY, DATE_OF_BIRTH)
VALUES ('Tech', '2', 'Nguy?n ?ình Sang', 'Fresher Mobile', 'Manager', '123456', TO_DATE('09-01-1999', 'dd-mm-yyyy'));

INSERT INTO EMPLOYEE (DEPARTMENT, EMPLOYEE_ID, EMPLOYEE_NAME, JOB_POSITION, MANAGER, SALARY, DATE_OF_BIRTH)
VALUES ('Tech', '3', 'Nguy?n ?ình Sang', 'Fresher Mobile', 'Manager', '250000', TO_DATE('09-01-1999', 'dd-mm-yyyy'));

INSERT INTO EMPLOYEE (DEPARTMENT, EMPLOYEE_ID, EMPLOYEE_NAME, JOB_POSITION, MANAGER, SALARY, DATE_OF_BIRTH)
VALUES ('Tech', '4', 'Nguy?n ?ình Sang', 'Fresher Mobile', 'Manager', '250000', TO_DATE('09-01-1999', 'dd-mm-yyyy'));

INSERT INTO EMPLOYEE (DEPARTMENT, EMPLOYEE_ID, EMPLOYEE_NAME, JOB_POSITION, MANAGER, SALARY, DATE_OF_BIRTH)
VALUES ('Tech', '5', 'Nguy?n ?ình Sang', 'Fresher Mobile', 'Manager', '500000', TO_DATE('09-01-1999', 'dd-mm-yyyy'));

INSERT INTO EMPLOYEE (DEPARTMENT, EMPLOYEE_ID, EMPLOYEE_NAME, JOB_POSITION, MANAGER, SALARY, DATE_OF_BIRTH)
VALUES ('FSA', '6', 'Sang ??p Trai', 'Senior%BA', 'Manager', '900000', TO_DATE('09-01-1999', 'dd-mm-yyyy'));