-- Employee
-- Cont 1 select basic
SELECT *
FROM EMPLOYEE;

SELECT EMPLOYEE_NAME, JOB_POSITION
FROM EMPLOYEE
WHERE EMPLOYEE_ID = 2;

-- Cont 2 select: null, alias, ||
SELECT EMPLOYEE_NAME, SALARY * NULL
FROM EMPLOYEE;

SELECT EMPLOYEE_NAME, SALARY + NULL AS ICOME
FROM EMPLOYEE;

SELECT EMPLOYEE_NAME AS NAME, DEPARTMENT AS DEP
FROM EMPLOYEE;
-->
SELECT EMPLOYEE_NAME || DEPARTMENT AS "NAME - DEP"
FROM EMPLOYEE;
