-- Cont 1
-- =, >, <, >=, <=, <> hoặc !=
SELECT EMPLOYEE_NAME || ' has a salary of ' || SALARY AS "NAME - SALARY"
FROM EMPLOYEE
WHERE SALARY > 200000;

-- Between and
SELECT *
FROM EMPLOYEE
WHERE SALARY BETWEEN 200000 AND 300000;

SELECT *
FROM EMPLOYEE
WHERE SALARY >= 200000 AND SALARY <= 300000;

-- In
SELECT *
FROM EMPLOYEE
WHERE EMPLOYEE_ID IN (1, 3, 5);

-- Like
-- % đại diện cho nhiều chuỗi, nhiều ký tự, hoặc giá trị 0
-- _ đại diện cho một ký tự hoặc giá trị 0

SELECT *
FROM EMPLOYEE
WHERE EMPLOYEE_NAME LIKE 'Nguyen%';

SELECT *
FROM EMPLOYEE
WHERE EMPLOYEE_NAME LIKE '%Sang';

SELECT *
FROM EMPLOYEE
WHERE EMPLOYEE_NAME LIKE '%D%';

SELECT *
FROM EMPLOYEE
WHERE EMPLOYEE_NAME LIKE '%?�nh%';

SELECT *
FROM EMPLOYEE;

SELECT *
FROM EMPLOYEE
WHERE DEPARTMENT LIKE '_ec_';

-- Xử lý ký tự % hoặc _ trong chuỗi bằng ESCAPE(\)
SELECT *
FROM EMPLOYEE
WHERE JOB_POSITION LIKE '%B_';

SELECT *
FROM EMPLOYEE
WHERE JOB_POSITION LIKE '%!%B_' ESCAPE '!';

-- Cont 2 
-- is null
SELECT *
FROM EMPLOYEE
WHERE MANAGER IS NULL;

-- Chỉ dùng is null không so sánh với null vì so sánh với null thì luôn null.

-- And, or, not
SELECT *
FROM EMPLOYEE
WHERE SALARY NOT IN(500000);

-- Cont 3 order by
SELECT *
FROM EMPLOYEE
ORDER BY SALARY DESC;













